name: pkbattles
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  zego_express_engine: ^3.11.0
  permission_handler: ^11.1.0
  encrypt: ^5.0.3
  zego_zim: ^2.13.0
  cached_network_image: ^3.3.0
  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
